---
title: "Titel"
author: "`r param$author`"
date: "`r format(Sys.time(), '%B, %Y')`"
geometry: "margin=2cm"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    code_folding: "hide"
    highlight: "tango"
    theme: "paper"
bibliography: "`r file.path(param$path_out, 'references.bib')`"
link-citations: yes
csl: "`r file.path(param$path_to_git, 'assets/elsevier-harvard.csl')`"
css: "`r file.path(param$path_to_git, 'assets/style.css')`"
---

```{r r_options, file='../../config/configuration.R'}
#source(file.path(param$path_to_git,'config/configuration.R'))
message("Set R options")
```

```{r rmarkdown, file='../../config/rmarkdown_configuration.R'}
#source(file.path(param$path_to_git,'config/rmarkdown_configuration.R'))
message("Set Rmarkdown options")
```

```{r load_packages, warning=FALSE, message=FALSE, results='hide'}

# Load renv
renv::load(file.path(param$path_to_git,"env/..."))

# Required libraries
library(...)

```



# Heading
 
Text

<br>


```{r chunk, warning=FALSE, message=FALSE}


```

```{r chunk_figure, fig.height=fig_standard_height, warning=FALSE, message=FALSE}


```

<br>
<br>
<br>

```{r, child='../export_data/appendix.Rmd'}
```

